---
# tasks file for ansible-role-ferm

- block:

  - name: install
    apt:
      name: "{{ ferm_dependencies + ferm_pkg is string | ternary([ferm_pkg], ferm_pkg) }}"
      state: present
      install_recommends: false
    tags:
      - install

  - name: setup
    template:
      src: ferm.conf.j2
      dest: /etc/ferm/ferm.conf
      owner: root
      group: root
      mode: u=rwX,go=rX
    notify: ferm restart
    tags:
      - setup

  become: true
  tags:
    - ferm
