---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: trusty
    image: ubuntu:trusty
    capabilities: ['NET_ADMIN']
  - name: xenial
    image: ubuntu:xenial
    capabilities: ['NET_ADMIN']
  - name: bionic
    image: ubuntu:bionic
    capabilities: ['NET_ADMIN']
  - name: stretch
    image: debian:stretch
    capabilities: ['NET_ADMIN']
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
